// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC84AzGM3Ev1a_iTC2WcA_31Z1xL7Y6yac',
    appId: '1:685583234612:web:808d637061a075f8f43c61',
    messagingSenderId: '685583234612',
    projectId: 'bringr-c710c',
    authDomain: 'bringr-c710c.firebaseapp.com',
    storageBucket: 'bringr-c710c.firebasestorage.app',
    measurementId: 'G-FG20GKSJQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2OOsWlKqYNAAzidldUDRYHCGxz9M-ok',
    appId: '1:685583234612:android:688b604a6dcd0229f43c61',
    messagingSenderId: '685583234612',
    projectId: 'bringr-c710c',
    storageBucket: 'bringr-c710c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAyMe0as5aM7WQWx4IrdsF6QJ8I6Ja_fU',
    appId: '1:685583234612:ios:bea6918c0d3ebabaf43c61',
    messagingSenderId: '685583234612',
    projectId: 'bringr-c710c',
    storageBucket: 'bringr-c710c.firebasestorage.app',
    iosBundleId: 'com.example.bringr',
  );
}
